### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Windows87** [Windows87/deeplab#1]
### Principal
- [x] Autenticação
- [x] Sobre Nós
- [x] Textos do Index

### Outras Ideias
- [ ] Favicon
- [x] Fazer Upload de Imagens
- [x] Página de Registro de Autores
- [x] Comentários em Artigos

### Cumprir com os Deveres
- [ ] Trocar as screenshots
